The ``--output_space`` option has been deprecated in version 1.4.0. Your selection of spaces "T1w, template, fsaverage5, fsnative" will be inserted at the front of the ``--output-spaces`` argument list. Please update your scripts to use ``--output-spaces``.
/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/layout.py:62: UserWarning: Accessing entities as attributes is deprecated as of 0.7. Please use the .entities dictionary instead (i.e., .entities['suffix'] instead of .suffix.
  % (attr, attr))
/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/layout.py:62: UserWarning: Accessing entities as attributes is deprecated as of 0.7. Please use the .entities dictionary instead (i.e., .entities['suffix'] instead of .suffix.
  % (attr, attr))
/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/layout.py:62: UserWarning: Accessing entities as attributes is deprecated as of 0.7. Please use the .entities dictionary instead (i.e., .entities['suffix'] instead of .suffix.
  % (attr, attr))
/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/layout.py:62: UserWarning: Accessing entities as attributes is deprecated as of 0.7. Please use the .entities dictionary instead (i.e., .entities['suffix'] instead of .suffix.
  % (attr, attr))
/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/layout.py:62: UserWarning: Accessing entities as attributes is deprecated as of 0.7. Please use the .entities dictionary instead (i.e., .entities['suffix'] instead of .suffix.
  % (attr, attr))
/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/layout.py:62: UserWarning: Accessing entities as attributes is deprecated as of 0.7. Please use the .entities dictionary instead (i.e., .entities['suffix'] instead of .suffix.
  % (attr, attr))
/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/layout.py:62: UserWarning: Accessing entities as attributes is deprecated as of 0.7. Please use the .entities dictionary instead (i.e., .entities['suffix'] instead of .suffix.
  % (attr, attr))
/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/layout.py:62: UserWarning: Accessing entities as attributes is deprecated as of 0.7. Please use the .entities dictionary instead (i.e., .entities['suffix'] instead of .suffix.
  % (attr, attr))
/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/layout.py:62: UserWarning: Accessing entities as attributes is deprecated as of 0.7. Please use the .entities dictionary instead (i.e., .entities['suffix'] instead of .suffix.
  % (attr, attr))
/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/layout.py:62: UserWarning: Accessing entities as attributes is deprecated as of 0.7. Please use the .entities dictionary instead (i.e., .entities['suffix'] instead of .suffix.
  % (attr, attr))
/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/layout.py:62: UserWarning: Accessing entities as attributes is deprecated as of 0.7. Please use the .entities dictionary instead (i.e., .entities['suffix'] instead of .suffix.
  % (attr, attr))
/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/layout.py:62: UserWarning: Accessing entities as attributes is deprecated as of 0.7. Please use the .entities dictionary instead (i.e., .entities['suffix'] instead of .suffix.
  % (attr, attr))
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/process.py", line 101, in _python_exit
    thread_wakeup.wakeup()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/process.py", line 89, in wakeup
    self._writer.send_bytes(b"")
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/connection.py", line 183, in send_bytes
    self._check_closed()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/connection.py", line 136, in _check_closed
    raise OSError("handle is closed")
OSError: handle is closed
(node:154881) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, lstat '/projects/adapt_lab/shared/TPOT/bids_data/derivatives/fmriprep/sub-TPOT092/ses-1/func/sub-TPOT092_ses-1_task-affect_acq-1_space-MNI152NLin2009cAsym_desc-aseg_dseg.nii.gz'
    at Object.lstatSync (fs.js:841:3)
    at isDirectory (/usr/lib/node_modules/bids-validator/utils/files/readDir.js:130:23)
    at files.map.file (/usr/lib/node_modules/bids-validator/utils/files/readDir.js:116:9)
    at Array.map (<anonymous>)
    at getFiles (/usr/lib/node_modules/bids-validator/utils/files/readDir.js:99:9)
    at files.map.file (/usr/lib/node_modules/bids-validator/utils/files/readDir.js:117:7)
    at Array.map (<anonymous>)
    at getFiles (/usr/lib/node_modules/bids-validator/utils/files/readDir.js:99:9)
    at files.map.file (/usr/lib/node_modules/bids-validator/utils/files/readDir.js:117:7)
    at Array.map (<anonymous>)
(node:154881) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:154881) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
The ``--output_space`` option has been deprecated in version 1.4.0. Your selection of spaces "T1w, template, fsaverage5, fsnative" will be inserted at the front of the ``--output-spaces`` argument list. Please update your scripts to use ``--output-spaces``.
/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/layout.py:62: UserWarning: Accessing entities as attributes is deprecated as of 0.7. Please use the .entities dictionary instead (i.e., .entities['suffix'] instead of .suffix.
  % (attr, attr))
/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/layout.py:62: UserWarning: Accessing entities as attributes is deprecated as of 0.7. Please use the .entities dictionary instead (i.e., .entities['suffix'] instead of .suffix.
  % (attr, attr))
/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/layout.py:62: UserWarning: Accessing entities as attributes is deprecated as of 0.7. Please use the .entities dictionary instead (i.e., .entities['suffix'] instead of .suffix.
  % (attr, attr))
/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/layout.py:62: UserWarning: Accessing entities as attributes is deprecated as of 0.7. Please use the .entities dictionary instead (i.e., .entities['suffix'] instead of .suffix.
  % (attr, attr))
/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/layout.py:62: UserWarning: Accessing entities as attributes is deprecated as of 0.7. Please use the .entities dictionary instead (i.e., .entities['suffix'] instead of .suffix.
  % (attr, attr))
/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/layout.py:62: UserWarning: Accessing entities as attributes is deprecated as of 0.7. Please use the .entities dictionary instead (i.e., .entities['suffix'] instead of .suffix.
  % (attr, attr))
exception calling callback for <Future at 0x2aaad2fcf400 state=finished raised OSError>
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 487, in run
    self, report_type='postexec', is_mapnode=isinstance(self, MapNode))
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 149, in write_report
    result = node.result  # Locally cache result
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 197, in result
    return _load_resultfile(self.output_dir(), self.name)[0]
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 359, in load_resultfile
    basedir=path).items()):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 478, in modify_paths
    val, relative=relative, basedir=basedir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 484, in modify_paths
    modify_paths(val, relative=relative, basedir=basedir))
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 498, in modify_paths
    raise IOError('File %s not found' % out)
OSError: File /projects/adapt_lab/shared/TPOT/bids_data/derivatives/working/fmriprep_wf/single_subject_TPOT021_wf/func_preproc_ses_1_task_video_wf/func_derivatives_wf/raw_sources/sub-TPOT021/ses-1/func/sub-TPOT021_ses-1_task-video_bold.nii.gz not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/process.py", line 232, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 72, in run_node
    result['result'] = node.result
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 197, in result
    return _load_resultfile(self.output_dir(), self.name)[0]
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 359, in load_resultfile
    basedir=path).items()):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 478, in modify_paths
    val, relative=relative, basedir=basedir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 484, in modify_paths
    modify_paths(val, relative=relative, basedir=basedir))
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 498, in modify_paths
    raise IOError('File %s not found' % out)
OSError: File /projects/adapt_lab/shared/TPOT/bids_data/derivatives/working/fmriprep_wf/single_subject_TPOT021_wf/func_preproc_ses_1_task_video_wf/func_derivatives_wf/raw_sources/sub-TPOT021/ses-1/func/sub-TPOT021_ses-1_task-video_bold.nii.gz not found
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 151, in _async_callback
    result = args.result()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
OSError: File /projects/adapt_lab/shared/TPOT/bids_data/derivatives/working/fmriprep_wf/single_subject_TPOT021_wf/func_preproc_ses_1_task_video_wf/func_derivatives_wf/raw_sources/sub-TPOT021/ses-1/func/sub-TPOT021_ses-1_task-video_bold.nii.gz not found
slurmstepd: error: *** JOB 9546194 ON n016 CANCELLED AT 2019-07-07T18:22:58 DUE TO TIME LIMIT ***
